pipeline {
    agent any

    environment {
        GOCACHE = '/tmp/go-build-cache'
        GOPATH  = '/tmp/go-path'
    }

    stages {
        stage('Unit tests - backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-backend') {
                    sh 'go test -v ./...'
                }
            }
        }
    }
}